// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1qxwhrPgzPp-e9hj8FaLqJSv6wJGno6Q',
    appId: '1:763075562228:web:5052f95e90564682dcaca1',
    messagingSenderId: '763075562228',
    projectId: 'proyeccion-53a2d',
    authDomain: 'proyeccion-53a2d.firebaseapp.com',
    storageBucket: 'proyeccion-53a2d.appspot.com',
    measurementId: 'G-1K3TCCPJJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKzi1-neo-fG1mvimCzoHhe5Nj644lIfg',
    appId: '1:763075562228:android:b5bc7597ce3c2e83dcaca1',
    messagingSenderId: '763075562228',
    projectId: 'proyeccion-53a2d',
    storageBucket: 'proyeccion-53a2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtkIVGYSvB1GtRcZGbHippVO_EnQF4glc',
    appId: '1:763075562228:ios:261852f7b9207400dcaca1',
    messagingSenderId: '763075562228',
    projectId: 'proyeccion-53a2d',
    storageBucket: 'proyeccion-53a2d.appspot.com',
    iosBundleId: 'com.example.sanPedroDeYauyo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtkIVGYSvB1GtRcZGbHippVO_EnQF4glc',
    appId: '1:763075562228:ios:261852f7b9207400dcaca1',
    messagingSenderId: '763075562228',
    projectId: 'proyeccion-53a2d',
    storageBucket: 'proyeccion-53a2d.appspot.com',
    iosBundleId: 'com.example.sanPedroDeYauyo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1qxwhrPgzPp-e9hj8FaLqJSv6wJGno6Q',
    appId: '1:763075562228:web:0815985caeee0935dcaca1',
    messagingSenderId: '763075562228',
    projectId: 'proyeccion-53a2d',
    authDomain: 'proyeccion-53a2d.firebaseapp.com',
    storageBucket: 'proyeccion-53a2d.appspot.com',
    measurementId: 'G-JY6YZL8GP0',
  );
}
